basePath: /v2
definitions:
  domain.Employee:
    properties:
      age:
        type: integer
      id:
        type: integer
      job:
        type: string
      name:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /employee:
    get:
      consumes:
      - application/json
      description: get all employees
      operationId: get-all-empls
      parameters:
      - description: Employee ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Employee'
            type: array
        "400":
          description: Bad Request
          schema:
            type: "No"
        "404":
          description: Not Found
          schema:
            type: "No"
      security:
      - ApiKeyAuth: []
      summary: Get All Employees
      tags:
      - Employee
    post:
      consumes:
      - application/json
      description: create employee
      operationId: create-empl
      parameters:
      - description: Employee info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: "No"
        "400":
          description: Bad Request
          schema:
            type: "No"
        "404":
          description: Not Found
          schema:
            type: "No"
      security:
      - ApiKeyAuth: []
      summary: Create Employee
      tags:
      - Employee
  /employee/{id}:
    get:
      consumes:
      - application/json
      description: get employee by id
      operationId: get-empl-by-id
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Employee'
        "400":
          description: Bad Request
          schema:
            type: "No"
        "404":
          description: Not Found
          schema:
            type: "No"
      security:
      - ApiKeyAuth: []
      summary: Get Employee By ID
      tags:
      - Employee
    post:
      consumes:
      - application/json
      description: delete employee by id
      operationId: delete-empl
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: "No"
        "400":
          description: Bad Request
          schema:
            type: "No"
        "404":
          description: Not Found
          schema:
            type: "No"
      security:
      - ApiKeyAuth: []
      summary: Delete Employee By ID
      tags:
      - Employee
    put:
      consumes:
      - application/json
      description: update employee
      operationId: update-empl
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: "No"
        "400":
          description: Bad Request
          schema:
            type: "No"
        "404":
          description: Not Found
          schema:
            type: "No"
      security:
      - ApiKeyAuth: []
      summary: Update Employee By ID
      tags:
      - Employee
swagger: "2.0"
